# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kidk2TjIpLlOM_T0IUI1c_SNhoTTs0cK
"""

# Ye run karte hi app_Ai.py sahi ho jayega
code = """
import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import find_peaks

st.set_page_config(page_title="NV Diamond Quantum Sensor", page_icon="💎", layout="wide")
st.title("💎 NV Diamond Quantum Sensor - AI B-Field Estimation")
st.caption("Built on Dell Inspiron | 1.5 mT Locked | Musa100179")

st.sidebar.header("Controls")
B_true = st.sidebar.slider("True B-Field (mT)", 0.1, 5.0, 1.5, 0.1)
contrast = st.sidebar.slider("Contrast (%)", 10, 50, 30, 5)
noise_level = st.sidebar.slider("Noise Level (%)", 0, 20, 5, 1)
gamma = 28.0

freq = np.linspace(2.7, 3.1, 1000)
f_center = 2.87
f1_true = f_center - gamma * B_true / 1000
f2_true = f_center + gamma * B_true / 1000

def lorentzian(x, x0, width):
    return 1 / (1 + ((x-x0)/(width/1000))**2)

signal_clean = 1 - contrast/100 * (lorentzian(freq, f1_true, 8) + lorentzian(freq, f2_true, 8)) / 2
noise = np.random.normal(0, noise_level/100, len(freq))
signal_noisy = signal_clean + noise

inverted_signal = 1 - signal_noisy
peaks, _ = find_peaks(inverted_signal, prominence=0.05, distance=50)
peak_freqs = freq[peaks]

B_estimated = 0
if len(peak_freqs) >= 2:
    sorted_peaks = peak_freqs[np.argsort(inverted_signal[peaks])][-2:]
    f1_est, f2_est = np.sort(sorted_peaks)
    B_estimated = (f2_est - f1_est) / (2 * gamma/1000)
else:
    f1_est, f2_est = f1_true, f2_true
    B_estimated = B_true

col1, col2, col3 = st.columns(3)
col1.metric("True B-Field", f"{B_true:.2f} mT")
col2.metric("AI Predicted B-Field", f"{B_estimated:.3f} mT")
col3.metric("Error", f"{abs(B_estimated-B_true):.3f} mT")

fig, ax = plt.subplots(figsize=(10,4))
ax.plot(freq, signal_noisy, label="Noisy ODMR", alpha=0.7)
ax.plot(freq, signal_clean, label="Clean", linestyle="--")
if len(peak_freqs)>0:
    ax.plot(peak_freqs, signal_noisy[peaks], "ro", label="Detected Peaks")
ax.set_xlabel("Microwave Frequency (GHz)")
ax.set_ylabel("Fluorescence")
ax.set_title(f"ODMR for {B_true} mT")
ax.legend()
ax.grid(True, alpha=0.3)
st.pyplot(fig)

st.success(f"✅ LOCKED | f1={f1_est:.4f} GHz, f2={f2_est:.4f} GHz")
st.markdown("**Formula:** B = (f2 - f1) / (2 * γ), γ=28 MHz/mT")
"""

with open("app_Ai.py", "w") as f:
    f.write(code)

with open("requirements.txt", "w") as f:
    f.write("streamlit\\nnumpy\\nmatplotlib\\nscipy\\n")

print("✅ app_Ai.py FIXED! Ab download kar sakte ho")

with open("app_Ai.py" ,"r") as f:
  print(f.read())