# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13AlTBSqg0vkaA9WC_SmLOUhKCYmYuD6s
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

np.random.seed(42) # Har bar same result

def nv_odmr(magnetic_field_uT, noise=0.001):
    freq = np.linspace(2.86e9, 2.88e9, 2000)
    zero_field = 2.87e9
    zeeman_shift = 200e3 * magnetic_field_uT # 150e3 se 200e3 kiya

    dip1 = zero_field + zeeman_shift # Right wala dip
    dip2 = zero_field - zeeman_shift # Left wala dip

    signal = 1.0
    signal -= 0.15 * np.exp(-((freq-dip1)/1e6)**2)
    signal -= 0.15 * np.exp(-((freq-dip2)/1e6)**2)
    signal += np.random.normal(0, noise, len(signal))
    return freq, signal, dip1, dip2 # dip positions bhi return karo

print("Generating 2000 fake sensor readings...")
X, y = [], []
for B in np.linspace(10, 40, 2000): # 10 se 40 tak
    freq, signal, d1, d2 = nv_odmr(B)
    dip_distance = abs(d1 - d2) # Direct doori nikal lo
    X.append([dip_distance])
    y.append(B)

X = np.array(X)
y = np.array(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
print(f"AI Accuracy: {model.score(X_test, y_test)*100:.2f}%")

test_B = 25.0
freq, signal, d1, d2 = nv_odmr(test_B)
dip_distance = abs(d1 - d2)
predicted_B = model.predict([[dip_distance]])[0]

# Graph plot
plt.figure(figsize=(11,5))
plt.plot(freq/1e9, signal, label=f"Sensor Signal")
plt.plot(d1/1e9, 1-0.15, 'ro', markersize=10, label=f"Right Dip")
plt.plot(d2/1e9, 1-0.15, 'ro', markersize=10, label=f"Left Dip")
plt.xlabel("Frequency (GHz)")
plt.ylabel("NV Glow Intensity")
plt.title(f"Virtual NV Sensor | Real B={test_B}uT | AI Predicted={predicted_B:.2f}uT")
plt.legend()
plt.grid(True)
plt.ylim(0.7, 1.05)
plt.show()

print(f"\nActual Magnetic Field: {test_B} uT")
print(f"AI Predicted Field: {predicted_B:.2f} uT")
print(f"Error: {abs(test_B - predicted_B):.3f} uT")
print(f"Physics Check: B = Distance / 400kHz = {dip_distance/400000:.2f} uT")